### PR TITLE
Handle MSI auth requests by ResourceID

### LINKED ISSUE #535: Arbitrary subscription used when pod has identities from multiple subscriptions
**Describe the bug**

I have a pod that matches 2 AzureIdentityBindings to user-assigned managed identities from 2 different subscriptions belonging to my tenant.

When a container in the pod uses the Azure CLI to log in to one of these identities, it is often logged in with the incorrect subscription, and does not have access to the correct subscription.

**Steps To Reproduce**

With the following AzureIdentity and AzureIdentityBindings defined:

```
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  annotations:
    aadpodidentity.k8s.io/Behavior: namespaced
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"aadpodidentity.k8s.io/v1","kind":"AzureIdentity","metadata":{"annotations":{"aadpodidentity.k8s.io/Behavior":"namespaced"},"name":"contoso-deployer-nonprod-client","namespace":"jenkins"},"spec":{"ClientID":"24a7d58c-XXXX-XXXX-XXXX-XXXXXXXXXXXX","ResourceID":"/subscriptions/a803e544-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourcegroups/contoso-deployer-nonprod/providers/Microsoft.ManagedIdentity/userAssignedIdentities/contoso-deployer-client","type":0}}
  creationTimestamp: "2020-03-02T15:29:06Z"
  generation: 1
  name: contoso-deployer-nonprod-client
  namespace: jenkins
  resourceVersion: "40262920"
  selfLink: /apis/aadpodidentity.k8s.io/v1/namespaces/jenkins/azureidentities/contoso-deployer-nonprod-client
  uid: 8deb3676-XXXX-XXXX-XXXX-XXXXXXXXXXXX
spec:
  ClientID: 24a7d58c-XXXX-XXXX-XXXX-XXXXXXXXXXXX
  ResourceID: /subscriptions/a803e544-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourcegroups/contoso-deployer-nonprod/providers/Microsoft.ManagedIdentity/userAssignedIdentities/contoso-deployer-client
  type: 0
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  annotations:
    aadpodidentity.k8s.io/Behavior: namespaced
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"aadpodidentity.k8s.io/v1","kind":"AzureIdentity","metadata":{"annotations":{"aadpodidentity.k8s.io/Behavior":"namespaced"},"name":"contoso-deployer-prod-client","namespace":"jenkins"},"spec":{"ClientID":"f8f978f8-XXXX-XXXX-XXXX-XXXXXXXXXXXX","ResourceID":"/subscriptions/1ea7fefd-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourcegroups/contoso-deployer-prod/providers/Microsoft.ManagedIdentity/userAssignedIdentities/contoso-deployer-client","type":0}}
  creationTimestamp: "2020-03-12T16:56:32Z"
  generation: 1
  name: contoso-deployer-prod-client
  namespace: jenkins
  resourceVersion: "42786887"
  selfLink: /apis/aadpodidentity.k8s.io/v1/namespaces/jenkins/azureidentities/contoso-deployer-prod-client
  uid: 6cf2d84e-XXXX-XXXX-XXXX-XXXXXXXXXXXX
spec:
  ClientID: f8f978f8-XXXX-XXXX-XXXX-XXXXXXXXXXXX
  ResourceID: /subscriptions/1ea7fefd-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourcegroups/contoso-deployer-prod/providers/Microsoft.ManagedIdentity/userAssignedIdentities/contoso-deployer-client
  type: 0
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"aadpodidentity.k8s.io/v1","kind":"AzureIdentityBinding","metadata":{"annotations":{},"name":"contoso-deployer-nonprod-combined-client","namespace":"jenkins"},"spec":{"AzureIdentity":"contoso-deployer-nonprod-client","Selector":"contoso-deployer-combined-client"}}
  creationTimestamp: "2020-03-18T18:08:26Z"
  generation: 1
  name: contoso-deployer-nonprod-combined-client
  namespace: jenkins
  resourceVersion: "44303967"
  selfLink: /apis/aadpodidentity.k8s.io/v1/namespaces/jenkins/azureidentitybindings/contoso-deployer-nonprod-combined-client
  uid: 7685afe8-XXXX-XXXX-XXXX-XXXXXXXXXXXX
spec:
  AzureIdentity: contoso-deployer-nonprod-client
  Selector: contoso-deployer-combined-client
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"aadpodidentity.k8s.io/v1","kind":"AzureIdentityBinding","metadata":{"annotations":{},"name":"contoso-deployer-prod-combined-client","namespace":"jenkins"},"spec":{"AzureIdentity":"contoso-deployer-prod-client","Selector":"contoso-deployer-combined-client"}}
  creationTimestamp: "2020-03-18T18:08:26Z"
  generation: 1
  name: contoso-deployer-prod-combined-client
  namespace: jenkins
  resourceVersion: "44303968"
  selfLink: /apis/aadpodidentity.k8s.io/v1/namespaces/jenkins/azureidentitybindings/contoso-deployer-prod-combined-client
  uid: 76908bab-XXXX-XXXX-XXXX-XXXXXXXXXXXX
spec:
  AzureIdentity: contoso-deployer-prod-client
  Selector: contoso-deployer-combined-client
```

Create a pod with the following label:  

```
     aadpodidbinding: "contoso-deployer-combined-client"
```

  In one of the pod’s containers, use the Azure CLI to log in with one of the managed identities. 

```
 + az login -i -u /subscriptions/a803e544-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/contoso-deployer-nonprod/providers/Microsoft.ManagedIdentity/userAssignedIdentities/contoso-deployer-client
[
  {
    "environmentName": "AzureCloud",
    "id": "1ea7fefd-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
    "isDefault": true,
    "name": "Contoso - Production",
    "state": "Enabled",
    "tenantId": "5f6f05d7-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
    "user": {
      "assignedIdentityInfo": "MSIResource-/subscriptions/a803e544-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/contoso-deployer-nonprod/providers/Microsoft.ManagedIdentity/userAssignedIdentities/contoso-deployer-client",
      "name": "userAssignedIdentity",
      "type": "servicePrincipal"
    }
  }
]
+ az account set -s a803e544-XXXX-XXXX-XXXX-XXXXXXXXXXXX
ERROR: The subscription of 'a803e544-XXXX-XXXX-XXXX-XXXXXXXXXXXX' doesn't exist in cloud 'AzureCloud'.
```

  Note that the `id` field in the `az login` response contains the subscription ID of the subscription containing the other managed identity.

**Expected behavior**  

The `id` field in the `az login` response would contain the subscription ID of the subscription containing the selected managed identity, and explicitly setting the subscription with `az account set` would succeed. This is the case when using an Azure VM without Kubernetes.

**AAD Pod Identity version**

1.5.5

**Kubernetes version**

1.14.6 in AKS

**Additional context**

### PR DESCRIPTION
**Pull request by carolynvs**
**Reason for Change**:

This allows someone to authenticate with a resource id, e.g. `az login -i -u /subscriptions/SUBID/resourcegroups/carolynvs-east/providers/Microsoft.ManagedIdentity/userAssignedIdentities/NAME` within a pod and have the correct identity resolved when multiple identities are resolvable.

**Issue Fixed**:

Fixes #535 

**Notes for Reviewers**:
* Since the adal go library doesn't support authenticating with a resource_id, only client_id, the solution looks up the proper client id from the configured AzureIdentities. There is still a gap if the user tried to authenticate using object_id, which is another supported parameter for that rest call that we are intercepting, but that field is not included on AzureIdentity. So I would consider this a short term solution until the library supports the endpoint completely.
* I introduced a `TokenRequest` struct to pass around the `ClientID`, `ResourceID`, and `Resource` from the intercepted request to prepare for a long term solution but avoided any refactoring to keep the PR scope focused. I think it could be useful to pass this around together, instead of as an eventual quadruplet of data (once we support `ObjectID` too).
* I wasn't able to run the e2e tests locally and could use some help with that. I manually reproduced and verified the fix, but I couldn't check if the regression test that I added to the e2e tests passes.

### CODE REVIEW

File: pkg/nmi/server/server.go [hunk 1]
```diff
@@ -218,18 +219,33 @@ func (s *Server) hostHandler(w http.ResponseWriter, r *http.Request) (ns string)
...
 	}
-	if !validateResourceParamExists(rqResource) {
+	if !tokenRequest.ValidateResourceParamExists() {
 		klog.Warning("parameter resource cannot be empty")
 		http.Error(w, "parameter resource cannot be empty", http.StatusBadRequest)
 		return
 	}
-	podID, err := s.TokenClient.GetIdentities(r.Context(), podns, podname, rqClientID)
+
+	if len(tokenRequest.ResourceID) > 0 {
```
Comment (aramase) [inline pkg/nmi/server/server.go]: So the filtering of `AzureIdentity` is done in `standard.go` and `managed.go`.

The user creates an `AzureIdentity`, `AzureIdentityBinding` and then the pods. When the pod gets created, MIC assigns the identity to the underlying node in case of standard mode and then creates an `AzureAssignedIdentity` which maps all 3 objects (azid, azidbinding and the pod). The `AzureAssignedIdentity` already contains the `AzureIdentity` ref which we use to filter [here](https://github.com/Azure/aad-pod-identity/blob/master/pkg/nmi/standard.go#L84-L151) based on clientID being present/not in the request. So we would need to move this logic into standard and managed modes.

File: pkg/crd/crd.go [hunk 2]
```diff
@@ -90,6 +88,12 @@ func NewCRDClientLite(config *rest.Config, nodeName string, scale, isStandardMod
 		return nil, err
 	}
 
+	idListInformer, err := newIDInformerLite(newIDListWatch(restClient))
```
Comment (aramase) [inline pkg/crd/crd.go]: We don't need a new informer for `AzureIdentity` in the standard mode `AzureAssignedIdentity` for the pod contains the `AzureIdentity` reference. We can lookup the clientID and resourceID from all the `AzureAssignedIdentities` that match for the pod.

The only reason we have the informer for managed mode is, there'll be no MIC in managed mode to do the assignment.  The Identity assignment will be done by RP or externally by running `az vm/vmss identity assign` command. In this mode, NMI will lookup `AzureIdentity by first matching labels on `AzureIdentityBinding` and the `Pod`.

File: pkg/crd/crd.go [hunk 3]
```diff
@@ -639,6 +644,24 @@ func (c *Client) ListPodIds(podns, podname string) (map[string][]aadpodid.AzureI
 	return idStateMap, nil
 }
 
+// LookupClientIDByResourceID returns the clientID associated with the
+// specified resourceID defined on AzureIdentifies defined in the given
+// namespace.
+func (c *Client) LookupClientIDByResourceID(ns, resourceID string) (clientID string, err error) {
```
Comment (aramase) [inline pkg/crd/crd.go]: We don't need this new method, because [ListPodIds](https://github.com/Azure/aad-pod-identity/blob/master/pkg/crd/crd.go#L625-L640) already gives us the `AzureIdentities` that match for the pod.

**Comment by carolynvs** [comment]
I've updated the implementation using your new guidance. I am still having trouble getting the e2e tests to run. 

Here is an example error in the mic logs that I see:

```
E0331 18:37:27.269320       1 vmss.go:77] Code="ManagedServiceIdentityAccessInternalError" Message="Internal error encountered when retrieving managed service identity details for 'https://control-eastus.identity.azure.net/subscriptions/9491dcfe-4a3c-4806-a1c9-61dde2354d03/resourcegroups/MC_carolynvs535_managed-identity_eastus/providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodepool1-39074670-vmss/credentials/v2/systemassigned'."
E0331 18:37:27.269398       1 mic.go:940] Updating msis on node aks-nodepool1-39074670-vmss, add [1], del [0] failed with error Code="ManagedServiceIdentityAccessInternalError" Message="Internal error encountered when retrieving managed service identity details for 'https://control-eastus.identity.azure.net/subscriptions/9491dcfe-4a3c-4806-a1c9-61dde2354d03/resourcegroups/MC_carolynvs535_managed-identity_eastus/providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodepool1-39074670-vmss/credentials/v2/systemassigned'."
I0331 18:37:27.297124       1 mic.go:964] Updating msis on node aks-nodepool1-39074670-vmss000000 failed, but identity keyvault-identity-binding has successfully been assigned to node
I0331 18:37:27.297174       1 crd.go:687] Updating assigned identity default/identity-validator-797cb5569f-spwx8-default-keyvault-identity status to Assigned
```

Along with this in the nmi logs
```
E0331 18:37:33.134239       1 server.go:375] failed to get service principal token for pod:default/identity-validator-797cb5569f-spwx8, adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"}
```

The expected identity was matched and assigned though just fine. I assume that I am still not doing something right to setup my e2e environment properly, perhaps a missing role assignment? When I test locally everything works fine so I'm not sure which part I am missing...

**Comment by aramase** [comment]
@carolynvs Thank you for updating the PR. I'll review it soon. While running on an AKS cluster with managed identity enabled, the role assignments required would be - https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.msi.md

But from the logs you posted, it doesn't look like an issue with permissions. I think it was an internal issue with managed identity RP.

**Comment by carolynvs** [comment]
I'm going to keep this in draft and try the e2e tests again later to see if it was just a transient service error. The changes in the first commit are all passing the unit tests but I haven't had a chance yet to see the e2e tests pass with my changes.

**Comment by aramase** [comment]
@carolynvs Went over the PR. The changes look good. Did you get a chance to run the e2e again? Let me know if you still have any issues running it. I would be happy to pair with you to see what the issue is.

**Comment by aramase** [comment]
@carolynvs Can we convert this draft to a PR? Let us know what we can do to help. The e2e tests have now been added as part of the CI.

**Comment by aramase** [comment]
@carolynvs Looks like the PR needs rebase. Would you be able to rebase the PR?

**Comment by carolynvs** [comment]
Rebased!

**Comment by aramase** [comment]
This is failing on lint errors - 

```
pkg/nmi/standard_test.go:272: File is not `gofmt`-ed with `-s` (gofmt)
				aadpodid.AssignedIDCreated: []aadpodid.AzureIdentity{
pkg/nmi/server/server.go:548: File is not `gofmt`-ed with `-s` (gofmt)

test/e2e/identityvalidator/identityvalidator.go:95:6: func authenticateWithMsiResourceId should be authenticateWithMsiResourceID (golint)
func authenticateWithMsiResourceId(msiEndpoint, resourceID, resource string) (*adal.Token, error) {
     ^
test/e2e/identityvalidator/identityvalidator.go:102:2: don't use underscores in Go names; var `msi_parameters` should be `msiParameters` (golint)
	msi_parameters := url.Values{}
	^
pkg/nmi/server/server.go:458:2: S1008: should use 'return len(r.Resource) != 0' instead of 'if len(r.Resource) == 0 { return false }; return true' (gosimple)
	if len(r.Resource) == 0 {
	^
Makefile:62: recipe for target 'lint' failed
make: *** [lint] Error 1
```

File: pkg/nmi/server/server.go [hunk 4]
```diff
@@ -430,13 +432,42 @@ func parseRemoteAddr(addr string) string {
...
+
+func parseTokenRequest(r *http.Request) (request TokenRequest) {
 	vals := r.URL.Query()
 	if vals != nil {
-		clientID = vals.Get("client_id")
-		resource = vals.Get("resource")
+		// These are mutually exclusive values (client_id, msi_resource_id)
+		request.ClientID = vals.Get("client_id")
+		request.ResourceID = vals.Get("msi_res_id")
+
```
Comment (chewong) [inline pkg/nmi/server/server.go:467]: nit: remove extra space

File: pkg/nmi/server/server.go [hunk 5]
```diff
@@ -17,15 +17,15 @@ import (
 	"syscall"
 	"time"
 
+	"github.com/Azure/go-autorest/autorest/adal"
```
Comment (chewong) [inline pkg/nmi/server/server.go:20]: nit: exporting external libraries should be placed after exporting internal libraries.
