### PR TITLE
test: convert e2e test cases from old to new framework (part 5)

### LINKED ISSUE #657: test: convert E2E test cases from old to new test framework
| Test Case                                                                                                                            | Status              |
|--------------------------------------------------------------------------------------------------------------------------------------|---------------------|
| `should pass the identity validating test`                                                                                           | Migrated in #650    |
| `should not pass the identity validating test if the AzureIdentity is deleted`                                                       | Migrated in #650    |
| `should not pass the identity validating test if the AzureIdentityBinding is deleted`                                                | Migrated in #650    |
| `should delete the AzureAssignedIdentity if the deployment is deleted`                                                               | Migrated in #650    |
| `should establish a new AzureAssignedIdentity and remove the old one when draining the node containing identity validator`           | Migrating in #664   |
| `should remove the correct identities when adding AzureIdentity and AzureIdentityBinding in order and removing them in random order` | Migrated in #650    |
| `should not alter the user assigned identity on VM after AAD pod identity is created and deleted`                                    | Migrated in #662    |
| `should cleanup iptable rules after deleting aad-pod-identity`                                                                       | Migrated in #650    |
| `should not alter the system assigned identity after creating and deleting pod identity`                                             | Migrated in #662    |
| `should create azureassignedidentities for 40 pods within ~2mins 30seconds`                                                          | Migrated in #650    |
| `should be backward compatible with old and new version of mic and nmi`                                                              | Migrating in #664   |
| `should not delete an in use identity from a vmss`                                                                                   | Migrated in #662    |
| `should not delete the Immutable Identity from vmss when the deployment is deleted`                                                  | Migrating in Part 5 |
| `should pass liveness probe test`                                                                                                    | Migrating in #664   |
| `should pass validation by bypassing nmi using azurepodidentityexception crd`                                                        | Migrating in Part 5 |
| `should pass identity validation with correct identity and fail with wrong identity`                                                 | Migrated in #656    |
| `should delete assigned identity when identity no longer exists on underlying node`                                                  | Migrated in #662    |
| `should pass multiple identity validating test even when MIC is failing over`                                                        | Migrating in #664   |
| `should assign identity with init containers`                                                                                        | Migrated in #656    |
| `should pass the identity format validation with gatekeeper constraint`                                                              | Migrated in Part 5  |
| `should assign new identity and remove old when AzureIdentity updated`                                                               | Migrated in #656    |
| `should assign the valid identity to the node when batch assigning identities that contain invalid identities`                       | Migrated in #656    |
| `should not unassign existing identity if we assign invalid identities`                                                              | Migrated in #656    |

### PR DESCRIPTION
**Pull request by chewong**
**Reason for Change**:

Follow-up PR for #664.

Converted the following test cases from old to new framework:
`should pass the identity format validation with gatekeeper constraint`
`should pass validation by bypassing NMI using AzurePodIdentityException CRD`
`should not delete the Immutable Identity from VMSS when the deployment is deleted`

Also removed two PR jobs that used the old test framework since all of the test cases have been converted to the new test framework.

**Issue Fixed**:

ref: #586 
fixes #657

**Notes for Reviewers**:

### CODE REVIEW

File: test/e2e_new/framework/azureidentity/azureidentity_helpers.go [hunk 1]
```diff
@@ -67,14 +58,22 @@ func Create(input CreateInput) *aadpodv1.AzureIdentity {
...
 	}
 
-	Eventually(func() error {
-		return input.Creator.Create(context.TODO(), azureIdentity)
-	}, createTimeout, createPolling).Should(Succeed())
+	// For gatekeeper test case
+	if input.InvalidResourceID {
+		azureIdentity.Spec.ResourceID = fmt.Sprintf(invalidResourceIDTemplate, input.Config.SubscriptionID, input.IdentityName)
+		Eventually(func() error {
+			return input.Creator.Create(context.TODO(), azureIdentity)
```
Comment (aramase) [inline test/e2e_new/framework/azureidentity/azureidentity_helpers.go:70]: Not a blocker for this PR, but we should define contexts with timeout/deadline to ensure the tests don't hang until the pipeline timeout.

Comment (chewong) [reply test/e2e_new/framework/azureidentity/azureidentity_helpers.go:70]: Sounds good
