### PR TITLE
Re-enable the UTs by using fake rest client

### LINKED ISSUE #243: Reenable UTs calling mock ListWatcher
**Describe the bug**
The UTs which call ListWatcher are commented out in #240  because of the bug: https://github.com/kubernetes/client-go/issues/352. This issue is raised to track, so that we can reenable when we find a solution for this issue.

**Steps To Reproduce**

**Expected behavior**

**AAD Pod Identity version**

**Kubernetes version**

**Additional context**

### PR DESCRIPTION
**Pull request by kkmsft**
**Reason for Change**:

When fake rest client is used, the UT eventually hits the issue in https://github.com/kubernetes/client-go/issues/352. This PR uses the rest client from the fake package and also adds the corresponding HTTP clients to return back the pods to simulate the original package behavior.

**Issue Fixed**:

Fixes #243 

**Notes for Reviewers**:

### CODE REVIEW

File: pkg/k8s/client_test.go [hunk 1]
```diff
@@ -32,79 +45,166 @@ func TestGetSecret(t *testing.T) {
...
+	kubeClient := &KubeClient{ClientSet: client, PodListWatch: podListWatch}
 
 	time.AfterFunc(time.Duration(1200*time.Millisecond), func() {
-		fakeClient.CoreV1().Pods("default").Create(pod)
+		testClientSet.AddPod(testPodName, testPodNs, testPodIP)
 	})
 
 	start := time.Now()
-	podNs, podName, err := kubeClient.GetPodName(podIP)
+	podNs, podName, _, _, err := kubeClient.GetPodInfo(podIP)
```
Comment (aramase) [inline pkg/k8s/client_test.go]: Should we also check the replica set name and labels are returned correctly?

Comment (kkmsft) [reply pkg/k8s/client_test.go]: Will add in future PR.
